name: Test Publisher
on:
  workflow_dispatch:
    inputs:
      publisher_payload:
        description: publisher_payload

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Publisher
        uses: AmazeeLabs/publisher@58d41fe4033cc9ae748d7b8bac905cf0ec063924
        with:
          success_env_var_name: ALL_GOOD
          cache_paths: |
            vendor
            cache
          cache_key: 'publisher'
          env_vars: '{"FOO": "bar"}'

      - name: Check env vars
        run: echo "FOO is $FOO"

      - name: Check cache
        run: |
          cat cache/foo.txt || true

      - name: Update cache
        run: |
          mkdir -p cache && echo "$RANDOM" > cache/foo.txt
          cat cache/foo.txt

      - name: Build
        run: |
          sleep 5
          echo "ALL_GOOD=1" >> $GITHUB_ENV
