name: Test Publisher
on:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Publisher
        uses: AmazeeLabs/publisher@edff5f985bff718cebe3ff1233551181d01e230a

      - name: Sleep
        run: sleep 20
